/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.31).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.OSCALSsp;
import io.swagger.model.OSCALSspUpdateExample;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-02-24T08:30:46.962624+01:00[Europe/Berlin]")
@Validated
public interface SystemSecurityPlansApi {

    @Operation(summary = "Associates a component with an OSCAL system security plan", description = "Adds the given component to the components within the given system security plan's system-implementation.", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan or component not found") })
    @RequestMapping(value = "/system-security-plans/{sspId}/components/{componentId}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> addComponentToSsp(@Parameter(in = ParameterIn.PATH, description = "System security plan ID", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.PATH, description = "Component ID to be associated with SSP", required=true, schema=@Schema()) @PathVariable("componentId") String componentId, @Parameter(in = ParameterIn.HEADER, description = "" ,schema=@Schema()) @RequestHeader(value="api_key", required=false) String apiKey);


    @Operation(summary = "Associates a party with an OSCAL system security plan", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan or party not found") })
    @RequestMapping(value = "/system-security-plans/{sspId}/parties/{partyId}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> addPartyToSsp(@Parameter(in = ParameterIn.PATH, description = "System security plan ID", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.PATH, description = "Party ID to be associated with SSP", required=true, schema=@Schema()) @PathVariable("partyId") String partyId, @Parameter(in = ParameterIn.HEADER, description = "" ,schema=@Schema()) @RequestHeader(value="api_key", required=false) String apiKey);


    @Operation(summary = "Adds a new OSCAL system security plan", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/system-security-plans",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> addSsp(@Parameter(in = ParameterIn.DEFAULT, description = "OSCAL system security plan object to be added", required=true, schema=@Schema()) @Valid @RequestBody OSCALSsp body);


    @Operation(summary = "Deletes an OSCAL system security plan", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan not found") })
    @RequestMapping(value = "/system-security-plans/{sspId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteSsp(@Parameter(in = ParameterIn.PATH, description = "System security plan ID to delete", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.HEADER, description = "" ,schema=@Schema()) @RequestHeader(value="api_key", required=false) String apiKey);


    @Operation(summary = "Searches for OSCAL system security plans by name", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OSCALSsp.class)))),
        
        @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/system-security-plans/search",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<OSCALSsp>> findSspsByName(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Terms to search for in system security plan names" ,required=true,schema=@Schema()) @Valid @RequestParam(value = "query", required = true) String query);


    @Operation(summary = "Finds an OSCAL system security plan by ID", description = "Returns a single OSCAL system security plan", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = OSCALSsp.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan not found") })
    @RequestMapping(value = "/system-security-plans/{sspId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<OSCALSsp> getSspById(@Parameter(in = ParameterIn.PATH, description = "ID of system security plan to return", required=true, schema=@Schema()) @PathVariable("sspId") String sspId);


    @Operation(summary = "Returns all OSCAL system security plans", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OSCALSsp.class)))) })
    @RequestMapping(value = "/system-security-plans",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<OSCALSsp>> getSsps();


    @Operation(summary = "Removes a component from an OSCAL system security plan", description = "Removes the given component from the components within the given system security plan's system-implementation.  This should also result in references under other parts of the schema such as inventory-items being removed. ", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan or component not found") })
    @RequestMapping(value = "/system-security-plans/{sspId}/components/{componentId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> removeComponentfromSsp(@Parameter(in = ParameterIn.PATH, description = "System security plan ID", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.PATH, description = "Component ID to be associated with SSP", required=true, schema=@Schema()) @PathVariable("componentId") String componentId, @Parameter(in = ParameterIn.HEADER, description = "" ,schema=@Schema()) @RequestHeader(value="api_key", required=false) String apiKey);


    @Operation(summary = "Removes a party from an OSCAL system security plan", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan or party not found") })
    @RequestMapping(value = "/system-security-plans/{sspId}/parties/{partyId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> removePartyfromSsp(@Parameter(in = ParameterIn.PATH, description = "System security plan ID", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.PATH, description = "Party ID to be associated with SSP", required=true, schema=@Schema()) @PathVariable("partyId") String partyId, @Parameter(in = ParameterIn.HEADER, description = "" ,schema=@Schema()) @RequestHeader(value="api_key", required=false) String apiKey);


    @Operation(summary = "Replaces an existing OSCAL system security plan", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Updated system security plan"),
        
        @ApiResponse(responseCode = "404", description = "System security plan not found"),
        
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        
        @ApiResponse(responseCode = "415", description = "Unsupported media type") })
    @RequestMapping(value = "/system-security-plans/{sspId}",
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> replaceSsp(@Parameter(in = ParameterIn.PATH, description = "ID of system security plan to replace.", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.DEFAULT, description = "System security plan object to be replaced.", required=true, schema=@Schema()) @Valid @RequestBody OSCALSsp body);


    @Operation(summary = "Updates an existing OSCAL system security plan", description = "", security = {
        @SecurityRequirement(name = "oscal_auth", scopes = {
            "write:catalogs",
"read:catalogs",
"write:profiles",
"read:profiles",
"write:componentDefinitions",
"read:componentDefinitions",
"write:ssps",
"read:ssps",
"write:parties",
"read:parties"        })    }, tags={ "OSCAL System Security Plan" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "System security plan not found"),
        
        @ApiResponse(responseCode = "405", description = "Validation exception") })
    @RequestMapping(value = "/system-security-plans/{sspId}",
        consumes = { "application/json" }, 
        method = RequestMethod.PATCH)
    ResponseEntity<Void> updateSsp(@Parameter(in = ParameterIn.PATH, description = "ID of system security plan to return", required=true, schema=@Schema()) @PathVariable("sspId") String sspId, @Parameter(in = ParameterIn.DEFAULT, description = "System security plan object to be updated", required=true, schema=@Schema()) @Valid @RequestBody OSCALSspUpdateExample body);

}

